//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soulful.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soulful.Core.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards and official game rules thanks to Cards Against Humanity.
        /// </summary>
        public static string App_CAHCredit {
            get {
                return ResourceManager.GetString("App_CAHCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards licensed under CC BY-NC-SA 2.0.
        /// </summary>
        public static string App_CAHLicense {
            get {
                return ResourceManager.GetString("App_CAHLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been exposed.
        /// </summary>
        public static string App_Subtitle {
            get {
                return ResourceManager.GetString("App_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soulful.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Cards.
        /// </summary>
        public static string Command_BrowseCards {
            get {
                return ResourceManager.GetString("Command_BrowseCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select favourite answer.
        /// </summary>
        public static string Command_CzarPickCards {
            get {
                return ResourceManager.GetString("Command_CzarPickCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string Command_JoinGame {
            get {
                return ResourceManager.GetString("Command_JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Selected Cards.
        /// </summary>
        public static string Command_PlayerPickCards {
            get {
                return ResourceManager.GetString("Command_PlayerPickCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        public static string Command_StartGame {
            get {
                return ResourceManager.GetString("Command_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DialogButton_No {
            get {
                return ResourceManager.GetString("DialogButton_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DialogButton_Yes {
            get {
                return ResourceManager.GetString("DialogButton_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game hasn&apos;t even started yet! Are you sure you want to quit?.
        /// </summary>
        public static string DialogMessage_ClientLeavingLobby {
            get {
                return ResourceManager.GetString("DialogMessage_ClientLeavingLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you&apos;ve been disconnected from the server, and we don&apos;t know why..
        /// </summary>
        public static string DialogMessage_Disconnected {
            get {
                return ResourceManager.GetString("DialogMessage_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t know how you&apos;ve done it... but you&apos;ve connected to the server with the wrong pin. Sorry bud, try again!.
        /// </summary>
        public static string DialogMessage_InvalidPin {
            get {
                return ResourceManager.GetString("DialogMessage_InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You&apos;ve been kicked from the game.
        /// </summary>
        public static string DialogMessage_KickedFromServer {
            get {
                return ResourceManager.GetString("DialogMessage_KickedFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t kick yourself, doofus.
        /// </summary>
        public static string DialogMessage_KickSelf {
            get {
                return ResourceManager.GetString("DialogMessage_KickSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like the host quit the game. Sorry!.
        /// </summary>
        public static string DialogMessage_ServerClosed {
            get {
                return ResourceManager.GetString("DialogMessage_ServerClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry bud, but this server&apos;s full. Try asking the host to increase the number of max players..
        /// </summary>
        public static string DialogMessage_ServerFull {
            get {
                return ResourceManager.GetString("DialogMessage_ServerFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People are already queueing up to play! Are you sure you want to deprive them of this wonderful opportunity by closing the server?.
        /// </summary>
        public static string DialogMessage_ServerLeavingLobby {
            get {
                return ResourceManager.GetString("DialogMessage_ServerLeavingLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server host changed the number of maximum players, and you didn&apos;t make the cut. If you&apos;ve got a problem, now would be a good time to take it up with the host..
        /// </summary>
        public static string DialogMessage_ServerLimitChanged {
            get {
                return ResourceManager.GetString("DialogMessage_ServerLimitChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to He dunnit!.
        /// </summary>
        public static string DialogTitle_BlameServer {
            get {
                return ResourceManager.GetString("DialogTitle_BlameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That... might&apos;ve been us?.
        /// </summary>
        public static string DialogTitle_Disconnected {
            get {
                return ResourceManager.GetString("DialogTitle_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hacker alert!.
        /// </summary>
        public static string DialogTitle_InvalidPin {
            get {
                return ResourceManager.GetString("DialogTitle_InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insecurity lvl 100.
        /// </summary>
        public static string DialogTitle_KickSelf {
            get {
                return ResourceManager.GetString("DialogTitle_KickSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter!.
        /// </summary>
        public static string DialogTitle_LeavingGame {
            get {
                return ResourceManager.GetString("DialogTitle_LeavingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black Cards.
        /// </summary>
        public static string Header_BlackCards {
            get {
                return ResourceManager.GetString("Header_BlackCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Browser.
        /// </summary>
        public static string Header_CardBrowser {
            get {
                return ResourceManager.GetString("Header_CardBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Cards.
        /// </summary>
        public static string Header_WhiteCards {
            get {
                return ResourceManager.GetString("Header_WhiteCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Pin.
        /// </summary>
        public static string Hint_GamePin {
            get {
                return ResourceManager.GetString("Hint_GamePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string Hint_PlayerName {
            get {
                return ResourceManager.GetString("Hint_PlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re in! Wait for the host to start!.
        /// </summary>
        public static string Label_ConnectedToServer {
            get {
                return ResourceManager.GetString("Label_ConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin:.
        /// </summary>
        public static string Label_GamePin {
            get {
                return ResourceManager.GetString("Label_GamePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Players.
        /// </summary>
        public static string Label_MaxPlayers {
            get {
                return ResourceManager.GetString("Label_MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (You).
        /// </summary>
        public static string Leaderboard_You {
            get {
                return ResourceManager.GetString("Leaderboard_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the rules/how-to-play.
        /// </summary>
        public static string ToolTip_CAHHelp {
            get {
                return ResourceManager.GetString("ToolTip_CAHHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        public static string ToolTip_KickPlayer {
            get {
                return ResourceManager.GetString("ToolTip_KickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string ToolTip_NavigateBack {
            get {
                return ResourceManager.GetString("ToolTip_NavigateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Pin.
        /// </summary>
        public static string ToolTip_RefreshGamePin {
            get {
                return ResourceManager.GetString("ToolTip_RefreshGamePin", resourceCulture);
            }
        }
    }
}
